spring:
  datasource:
    url: jdbc:h2:mem:/data/ecdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled=true:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

schedule:
  cron:
    cleanInactivityCart: 0 0/1 * * * ?

